[symlinks]
"alacritty/alacritty.toml" = "/home/alchemmist/.config/alacritty/alacritty.toml"
"git/.gitconfig" = "/home/alchemmist/.gitconfig"
"hypr/hypridle.conf" = "/home/alchemmist/.config/hypr/hypridle.conf"
"hypr/hyprland.conf" = "/home/alchemmist/.config/hypr/hyprland.conf"
"hypr/hyprlock.conf" = "/home/alchemmist/.config/hypr/hyprlock.conf"
"kitty/gruvbox.conf" = "/home/alchemmist/.config/kitty/gruvbox.conf"
"kitty/kitty.conf" = "/home/alchemmist/.config/kitty/kitty.conf"
"kitty/mocha.conf" = "/home/alchemmist/.config/kitty/mocha.conf"
"nvim/init.lua" = "/home/alchemmist/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "/home/alchemmist/.config/nvim/lazy-lock.json"
"nvim/lua/core/bootstrap.lua" = "/home/alchemmist/.config/nvim/lua/core/bootstrap.lua"
"nvim/lua/core/default_config.lua" = "/home/alchemmist/.config/nvim/lua/core/default_config.lua"
"nvim/lua/core/init.lua" = "/home/alchemmist/.config/nvim/lua/core/init.lua"
"nvim/lua/core/mappings.lua" = "/home/alchemmist/.config/nvim/lua/core/mappings.lua"
"nvim/lua/core/utils.lua" = "/home/alchemmist/.config/nvim/lua/core/utils.lua"
"nvim/lua/custom/README.md" = "/home/alchemmist/.config/nvim/lua/custom/README.md"
"nvim/lua/custom/chadrc.lua" = "/home/alchemmist/.config/nvim/lua/custom/chadrc.lua"
"nvim/lua/custom/configs/lspconfig.lua" = "/home/alchemmist/.config/nvim/lua/custom/configs/lspconfig.lua"
"nvim/lua/custom/configs/null-ls.lua" = "/home/alchemmist/.config/nvim/lua/custom/configs/null-ls.lua"
"nvim/lua/custom/configs/overrides.lua" = "/home/alchemmist/.config/nvim/lua/custom/configs/overrides.lua"
"nvim/lua/custom/highlights.lua" = "/home/alchemmist/.config/nvim/lua/custom/highlights.lua"
"nvim/lua/custom/init.lua" = "/home/alchemmist/.config/nvim/lua/custom/init.lua"
"nvim/lua/custom/mappings.lua" = "/home/alchemmist/.config/nvim/lua/custom/mappings.lua"
"nvim/lua/custom/plugins.lua" = "/home/alchemmist/.config/nvim/lua/custom/plugins.lua"
"nvim/lua/plugins/configs/cmp.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/cmp.lua"
"nvim/lua/plugins/configs/lazy_nvim.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/lazy_nvim.lua"
"nvim/lua/plugins/configs/lspconfig.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/lspconfig.lua"
"nvim/lua/plugins/configs/mason.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/mason.lua"
"nvim/lua/plugins/configs/nvimtree.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/nvimtree.lua"
"nvim/lua/plugins/configs/others.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/others.lua"
"nvim/lua/plugins/configs/telescope.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/telescope.lua"
"nvim/lua/plugins/configs/treesitter.lua" = "/home/alchemmist/.config/nvim/lua/plugins/configs/treesitter.lua"
"nvim/lua/plugins/init.lua" = "/home/alchemmist/.config/nvim/lua/plugins/init.lua"
"scripts/swww_random.sh" = "/home/alchemmist/scripts/swww_random.sh"
"scripts/tdm.sh" = "/home/alchemmist/scripts/tdm.sh"
"scripts/wallpaper_pack_selector.sh" = "/home/alchemmist/scripts/wallpaper_pack_selector.sh"
"ssh/config" = "/home/alchemmist/.ssh/config"
"sway/config" = "/home/alchemmist/.config/sway/config"
"tmux/.tmux.conf" = "/home/alchemmist/.tmux.conf"
"tmux/.tmux.conf.local" = "/home/alchemmist/.tmux.conf.local"
"waybar/hypr-config.json" = "/home/alchemmist/.config/waybar/hypr-config.json"
"waybar/hypr-style.css" = "/home/alchemmist/.config/waybar/hypr-style.css"
"waybar/scripts/baraction" = "/home/alchemmist/.config/waybar/scripts/baraction"
"waybar/scripts/update-sys" = "/home/alchemmist/.config/waybar/scripts/update-sys"
"waybar/scripts/waybar-wttr.py" = "/home/alchemmist/.config/waybar/scripts/waybar-wttr.py"
"waybar/style/style-dark.css" = "/home/alchemmist/.config/waybar/style/style-dark.css"
"waybar/style/style.css" = "/home/alchemmist/.config/waybar/style/style.css"
"waybar/sway-config.json" = "/home/alchemmist/.config/waybar/sway-config.json"
"waybar/sway-style.css" = "/home/alchemmist/.config/waybar/sway-style.css"
"wlinitrc/wlinitrc" = "/home/alchemmist/.local/bin/wlinitrc"
"wofi/config" = "/home/alchemmist/.config/wofi/config"
"wofi/style/style-dark.css" = "/home/alchemmist/.config/wofi/style/style-dark.css"
"wofi/style/style.css" = "/home/alchemmist/.config/wofi/style/style.css"
"wofi/style.css" = "/home/alchemmist/.config/wofi/style.css"
"zsh/.zshrc" = "/home/alchemmist/.zshrc"

[templates]
