[default]
depends = [
    "zsh", 
    "waybar", 
    "hyprland",
    "tmux",
    "sway",
    "nvim",
    "wofi",
]


[zsh.files]
"zsh/.zshrc" = "~/.zshrc"

[waybar.files]
"waybar" = "~/.config/waybar"

[hyprland.files]
"hypr" = "~/.config/hypr"

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"
"tmux/.tmux.conf.local" = "~/.tmux.conf.local"

[sway.files]
"sway" = "~/.config/sway"

[nvim.files]
"nvim" = "~/.config/nvim"

[wofi.files]
"wofi" = "~/.config/wofi"
